---
title: "type_reclassification_sankey"
output: html_document
date: "2024-07-27"
---

```{r}

set.seed(111)

t1 <- sample(x = c("Type 1a", "Type 2a", "Othera") , size = 10, replace=TRUE)
t2 <- sample(x = c("Type 1b", "Type 2b", "Otherb")   , size = 10, replace=TRUE)
t3 <- sample(x = c("Type 1c", "Type 2c", "Otherc") , size = 10, replace=TRUE)

d <- data.frame(cbind(t1,t2,t3))

names(d) <- c('Hospital', 'Gender', 'Outcome')


df <- data_to_sankey(d)


# Change the node colours as shown below. Give the node name of each of your nodes and set the colour manually

plot <- highchart() %>%
     hc_add_series(data = data_to_sankey(d), type = "sankey"
                ,   hcaes(from = from, to = to, weight = weight)
                ,   nodes = list(list(id = 'Type 1a'  , color = "#F7CA1E")
                                 ,list(id = 'Type 1b' , color = "#F7CA1E")
                                 ,list(id = 'Type 1c'   , color = "#F7CA1E")
                                ,list(id = "Type 2a"  , color = "#B0E0E7")
                                ,list(id = "Type 2b"  , color = "#B0E0E7")
                                ,list(id = "Type 2c"    , color = "#B0E0E7")
                                ,list(id = "Othera"  , color = "#435CA4")
                                ,list(id = "Otherb"  , color = "#435CA4")
                                ,list(id = "Otherc"    , color = "#435CA4")
                                ))



plot


```



```{r}



set.seed(111)

t1 <- sample(x = c("Type 1", "Type 2", "Other", "NOS") , size = 10, replace=TRUE)
t2 <- sample(x = c("Type 1 ", "Type 2 ", "Other ", "NOS ")   , size = 10, replace=TRUE)
t3 <- sample(x = c("Type 1  ", "Type 2  ", "Other  ", "NOS  ") , size = 10, replace=TRUE)

d <- data.frame(cbind(t1,t2,t3))

d = d %>% mutate(t1=factor(t1,levels=c("Type 1","Type 2","Other","NOS"))) %>%
  mutate(t2=factor(t2,levels=c("Type 1 ", "Type 2 ", "Other ", "NOS "))) %>%
mutate(t3=factor(t3,levels=c("Type 1  ", "Type 2  ", "Other  ", "NOS  ")))


names(d) <- c('2020', '2021', '2022')


df <- data_to_sankey(d)


# Change the node colours as shown below. Give the node name of each of your nodes and set the colour manually

plot <- highchart() %>%
     hc_add_series(data = data_to_sankey(d), type = "sankey"
                ,   hcaes(from = from, to = to, weight = weight)
                ,   nodes = list(list(id = 'Type 1'  , color = "#F7CA1E")
                                 ,list(id = 'Type 1 ' , color = "#F7CA1E")
                                 ,list(id = 'Type 1  '   , color = "#F7CA1E")
                                ,list(id = "Type 2"  , color = "#B0E0E7")
                                ,list(id = "Type 2 "  , color = "#B0E0E7")
                                ,list(id = "Type 2  "    , color = "#B0E0E7")
                                ,list(id = "NOS"  , color = "#39AE89")
                                ,list(id = "NOS "  , color = "#39AE89")
                                ,list(id = "NOS  "    , color = "#39AE89")
                                ,list(id = "Other"  , color = "#435CA4")
                                ,list(id = "Other "  , color = "#435CA4")
                                ,list(id = "Other  "    , color = "#435CA4")
                                )) %>%
  hc_tooltip(formatter = JS("function() {
    if (this.point.isNode) {
      return false; // Do not show tooltip for nodes
    }
    return this.series.name.replace('Series 1', '') + '<br>' +
           this.point.from + ' → ' + this.point.to + ': ' + this.point.weight;
  }")) %>%
  # hc_chart(marginTop = 50) %>%
  # hc_annotations(list(
  #   labels = list(
  #     list(point = list(x = 0, y = 0), text = "2020", x = 0, y = -30
  #          ),
  #     list(point = list(x = 400, y = 0), text = "2021", x = 2, y = -30),
  #     list(point = list(x = 900, y = 0), text = "2022", x = 5, y = -30)
  #   ),
  #   draggable = ""
  # )) %>%
  hc_chart(marginTop = 50, events = list(
    load = JS("function() {
      this.renderer.text('2020', 10, 25)
        .css({
          color: 'black',
          fontSize: '14px',
          fontWeight: 'bold'
        })
        .add();
      this.renderer.text('2021', this.chartWidth / 2 - 20, 25)
        .css({
          color: 'black',
          fontSize: '14px',
          fontWeight: 'bold'
        })
        .add();
      this.renderer.text('2022', this.chartWidth - 45, 25)
        .css({
          color: 'black',
          fontSize: '14px',
          fontWeight: 'bold'
        })
        .add();
    }")
  ))



plot


```



